const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sourcePath = path.join(root, "src", "instagram-unfollower.js");
const distDir = path.join(root, "dist");
const distPath = path.join(distDir, "instagram-unfollower.one-line.js");
const hashModulePath = path.join(root, "functions", "api", "_script-hash.js");

const raw = fs.readFileSync(sourcePath, "utf8").replace(/^\uFEFF/, "");

/* The output only needs to be a pasteable one-liner, not an aggressively
   minified bundle. We strip comment-only lines and standalone block comments,
   then trim and join. Inline `//` comments are intentionally not stripped to
   avoid breaking URLs in strings. Keep the source free of inline comments. */

const stripped = raw
  .split(/\r?\n/)
  .map((line) => (/^\s*\/\//.test(line) ? "" : line))
  .join("\n")
  .replace(/\/\*[\s\S]*?\*\//g, " ");

const oneLine = stripped
  .split(/\r?\n/)
  .map((line) => line.trim())
  .filter(Boolean)
  .join(" ");

const output = oneLine + "\n";

fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(distPath, output, "utf8");

/* The security page advertises a SHA-256 for the file visitors actually copy.
   Deriving it here keeps that claim honest; a hand-pinned constant silently
   goes stale on the next build and ends up vouching for a different file. */
const fileHash = crypto.createHash("sha256").update(output, "utf8").digest("hex");
fs.writeFileSync(
  hashModulePath,
  `/* Generated by scripts/build.js. Do not edit by hand. */\nexport const FILE_HASH = ${JSON.stringify(fileHash)};\n`,
  "utf8"
);

/* The site reads changelog.json straight from the repo root, so a typo here
   would surface as a silently missing section. Fail the build instead. */
const changelogPath = path.join(root, "changelog.json");
const entries = JSON.parse(fs.readFileSync(changelogPath, "utf8"));
if (!Array.isArray(entries) || entries.length === 0) {
  throw new Error("changelog.json must be a non-empty array");
}
entries.forEach((entry, index) => {
  const where = `changelog.json[${index}]`;
  if (!/^\d+\.\d+\.\d+$/.test(entry.version || "")) {
    throw new Error(`${where}: version must look like 1.2.3`);
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(entry.date || "")) {
    throw new Error(`${where}: date must be YYYY-MM-DD`);
  }
  for (const lang of ["tr", "en"]) {
    if (!Array.isArray(entry[lang]) || entry[lang].length === 0) {
      throw new Error(`${where}: "${lang}" must be a non-empty array of strings`);
    }
    if (entry[lang].some((line) => typeof line !== "string" || !line.trim())) {
      throw new Error(`${where}: every "${lang}" entry must be a non-empty string`);
    }
  }
});
const sorted = entries.every((entry, i) => i === 0 || entries[i - 1].date >= entry.date);
if (!sorted) {
  throw new Error("changelog.json must be ordered newest first");
}

console.log(`Built ${path.relative(root, distPath)}`);
console.log(`${oneLine.length.toLocaleString()} characters`);
console.log(`SHA-256 ${fileHash}`);
console.log(`Changelog ${entries.length} entries, latest ${entries[0].version} (${entries[0].date})`);
