const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sourcePath = path.join(root, "src", "instagram-unfollower.js");
const distDir = path.join(root, "dist");
const distPath = path.join(distDir, "instagram-unfollower.one-line.js");
const hashModulePath = path.join(root, "functions", "api", "_script-hash.js");

const raw = fs.readFileSync(sourcePath, "utf8").replace(/^\uFEFF/, "");

/* The output only needs to be a pasteable one-liner, not an aggressively
   minified bundle. We strip comment-only lines and standalone block comments,
   then trim and join. Inline `//` comments are intentionally not stripped to
   avoid breaking URLs in strings. Keep the source free of inline comments. */

const stripped = raw
  .split(/\r?\n/)
  .map((line) => (/^\s*\/\//.test(line) ? "" : line))
  .join("\n")
  .replace(/\/\*[\s\S]*?\*\//g, " ");

const oneLine = stripped
  .split(/\r?\n/)
  .map((line) => line.trim())
  .filter(Boolean)
  .join(" ");

const output = oneLine + "\n";

fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(distPath, output, "utf8");

/* The security page advertises a SHA-256 for the file visitors actually copy.
   Deriving it here keeps that claim honest; a hand-pinned constant silently
   goes stale on the next build and ends up vouching for a different file. */
const fileHash = crypto.createHash("sha256").update(output, "utf8").digest("hex");
fs.writeFileSync(
  hashModulePath,
  `/* Generated by scripts/build.js. Do not edit by hand. */\nexport const FILE_HASH = ${JSON.stringify(fileHash)};\n`,
  "utf8"
);

console.log(`Built ${path.relative(root, distPath)}`);
console.log(`${oneLine.length.toLocaleString()} characters`);
console.log(`SHA-256 ${fileHash}`);
