name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  semgrep:
    name: semgrep/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto
